#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.
# # How I solved it: delete the existing ../sites-enabled/default and replace it with a copy of
# # NB: The flag -s creates a symbolic link, -f deletes the existing file and replaces it
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
